version: '3.8'
services:
  train:
    build: 
      context: .
      dockerfile: ./train/Dockerfile.train

    volumes:
      - mnist:/workspace/mnist
    
    restart: on-failure

    # Run the training command
    command: python train.py

  evaluate:
    build: 
      context: .
      dockerfile: ./eval/Dockerfile.eval

    volumes:
      - mnist:/workspace/mnist
    
    restart: on-failure

    # Run the evaluation command
    command: python eval.py

  infer:
    build: 
      context: .
      dockerfile: ./infer/Dockerfile.infr

    volumes:
      - mnist:/workspace/mnist
    
    restart: on-failure

    # Run the inference command
    command: python infer.py
volumes:
  mnist: