FROM python:3.9-slim

WORKDIR /workspace

# //copy requirements from parent directory
COPY requirements.txt .

RUN pip3 install -r requirements.txt && rm -rf /root/.cache/pip

COPY ./train .
COPY ./model .